//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonsDBEntities : DbContext
    {
        public PersonsDBEntities()
            : base("name=PersonsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Department> Departments { get; set; }
        public DbSet<EduField> EduFields { get; set; }
        public DbSet<EduLevel> EduLevels { get; set; }
        public DbSet<EduTendency> EduTendencies { get; set; }
        public DbSet<EmailContact> EmailContacts { get; set; }
        public DbSet<EmailType> EmailTypes { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Faculty> Faculties { get; set; }
        public DbSet<Lecturer> Lecturers { get; set; }
        public DbSet<PersonsAdmin> PersonsAdmins { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<TelContact> TelContacts { get; set; }
        public DbSet<TelType> TelTypes { get; set; }
        public DbSet<VPN> VPNs { get; set; }
        public DbSet<WebServiceAccount> WebServiceAccounts { get; set; }
        public DbSet<VEduTendency> VEduTendencies { get; set; }
        public DbSet<VEmailContact> VEmailContacts { get; set; }
        public DbSet<VEmployee> VEmployees { get; set; }
        public DbSet<VLecturer> VLecturers { get; set; }
        public DbSet<VStudent> VStudents { get; set; }
        public DbSet<VTelContact> VTelContacts { get; set; }
        public DbSet<VVPN> VVPNs { get; set; }
    }
}
