//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VVPN
    {
        public int VPNID { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string VPNDescription { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public string DepartmentTitle { get; set; }
    }
}
