//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DashboardText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DashboardText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال بودن حساب کاربری.
        /// </summary>
        internal static string ActiveAccount {
            get {
                return ResourceManager.GetString("ActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن واحد اداری معاونت.
        /// </summary>
        internal static string AddDepartment {
            get {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن رشته های تحصیلی.
        /// </summary>
        internal static string AddEduField {
            get {
                return ResourceManager.GetString("AddEduField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن سطح تحصیلی.
        /// </summary>
        internal static string AddEduLevel {
            get {
                return ResourceManager.GetString("AddEduLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن گرایش.
        /// </summary>
        internal static string AddEduTendency {
            get {
                return ResourceManager.GetString("AddEduTendency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن ایمیل.
        /// </summary>
        internal static string AddEmail {
            get {
                return ResourceManager.GetString("AddEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن ایمیل اشخاص.
        /// </summary>
        internal static string AddEmailContact {
            get {
                return ResourceManager.GetString("AddEmailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن نوع ایمیل.
        /// </summary>
        internal static string AddEmailType {
            get {
                return ResourceManager.GetString("AddEmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن کارمند.
        /// </summary>
        internal static string AddEmploye {
            get {
                return ResourceManager.GetString("AddEmploye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن دانشکده.
        /// </summary>
        internal static string AddFaculty {
            get {
                return ResourceManager.GetString("AddFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن رشته.
        /// </summary>
        internal static string AddField {
            get {
                return ResourceManager.GetString("AddField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن استاد.
        /// </summary>
        internal static string AddLecture {
            get {
                return ResourceManager.GetString("AddLecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن مدیران سامانه.
        /// </summary>
        internal static string AddPersonAdmin {
            get {
                return ResourceManager.GetString("AddPersonAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن سمت.
        /// </summary>
        internal static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن دانشجو.
        /// </summary>
        internal static string AddStudent {
            get {
                return ResourceManager.GetString("AddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن شماره تماس.
        /// </summary>
        internal static string AddTel {
            get {
                return ResourceManager.GetString("AddTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن نوع شماره تماس.
        /// </summary>
        internal static string AddTelType {
            get {
                return ResourceManager.GetString("AddTelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن vpn.
        /// </summary>
        internal static string AddVPN {
            get {
                return ResourceManager.GetString("AddVPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن اکانت وب سرویس.
        /// </summary>
        internal static string AddWebService {
            get {
                return ResourceManager.GetString("AddWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdminI {
            get {
                return ResourceManager.GetString("AdminI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه حساب.
        /// </summary>
        internal static string AdminID {
            get {
                return ResourceManager.GetString("AdminID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا برای حذف رکورد(های) انتخابی اطمینان دارید؟.
        /// </summary>
        internal static string AskToDelete {
            get {
                return ResourceManager.GetString("AskToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سامانه مدیریت  پرسنلی.
        /// </summary>
        internal static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پانل مدیریتی.
        /// </summary>
        internal static string Controlpanel {
            get {
                return ResourceManager.GetString("Controlpanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمامی حقوق برای آی تی بنیاد محفوظ است.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد واحد اداری.
        /// </summary>
        internal static string DepartmentID {
            get {
                return ResourceManager.GetString("DepartmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت واحدهای اداری.
        /// </summary>
        internal static string DepartmentManagment {
            get {
                return ResourceManager.GetString("DepartmentManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام واحد اداری.
        /// </summary>
        internal static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحدهای اداری معاونت.
        /// </summary>
        internal static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام واحد اداری.
        /// </summary>
        internal static string DepartmentTitle {
            get {
                return ResourceManager.GetString("DepartmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dsfs.
        /// </summary>
        internal static string dsfsd {
            get {
                return ResourceManager.GetString("dsfsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش واحد اداری معاونت.
        /// </summary>
        internal static string EditDepartment {
            get {
                return ResourceManager.GetString("EditDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش رشته های تحصیلی.
        /// </summary>
        internal static string EditEduField {
            get {
                return ResourceManager.GetString("EditEduField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش سطح تحصیلی.
        /// </summary>
        internal static string EditEduLevel {
            get {
                return ResourceManager.GetString("EditEduLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش گرایش.
        /// </summary>
        internal static string EditEduTendency {
            get {
                return ResourceManager.GetString("EditEduTendency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش ایمیل.
        /// </summary>
        internal static string editEmail {
            get {
                return ResourceManager.GetString("editEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش ایمیل اشخاص.
        /// </summary>
        internal static string EditEmailContact {
            get {
                return ResourceManager.GetString("EditEmailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش نوع ایمیل.
        /// </summary>
        internal static string EditEmailType {
            get {
                return ResourceManager.GetString("EditEmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش کارمند.
        /// </summary>
        internal static string EditEmploye {
            get {
                return ResourceManager.GetString("EditEmploye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش دانشکده.
        /// </summary>
        internal static string EditFaculty {
            get {
                return ResourceManager.GetString("EditFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش استاد.
        /// </summary>
        internal static string EditLecture {
            get {
                return ResourceManager.GetString("EditLecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش اکانت مدیران سامانه.
        /// </summary>
        internal static string EditPersonAdmin {
            get {
                return ResourceManager.GetString("EditPersonAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش سمت.
        /// </summary>
        internal static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش دانشجو.
        /// </summary>
        internal static string EditStudent {
            get {
                return ResourceManager.GetString("EditStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش شماره تماس.
        /// </summary>
        internal static string EditTel {
            get {
                return ResourceManager.GetString("EditTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش نوع شماره تماس.
        /// </summary>
        internal static string EditTelType {
            get {
                return ResourceManager.GetString("EditTelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش اکانت وب سرویس.
        /// </summary>
        internal static string EditWebService {
            get {
                return ResourceManager.GetString("EditWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت رشته های تحصیلی.
        /// </summary>
        internal static string EduFieldManagment {
            get {
                return ResourceManager.GetString("EduFieldManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته های تحصیلی.
        /// </summary>
        internal static string EduFields {
            get {
                return ResourceManager.GetString("EduFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت مقاطع تحصیلی.
        /// </summary>
        internal static string EduLevelManagment {
            get {
                return ResourceManager.GetString("EduLevelManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقاطع تحصیلی.
        /// </summary>
        internal static string EduLevels {
            get {
                return ResourceManager.GetString("EduLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گرایش ها.
        /// </summary>
        internal static string EduTendencies {
            get {
                return ResourceManager.GetString("EduTendencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت گرایش ها.
        /// </summary>
        internal static string EduTendencyManagment {
            get {
                return ResourceManager.GetString("EduTendencyManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت ایمیل ها.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل.
        /// </summary>
        internal static string EmailAddrress {
            get {
                return ResourceManager.GetString("EmailAddrress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل.
        /// </summary>
        internal static string EmailContact {
            get {
                return ResourceManager.GetString("EmailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ایمیل.
        /// </summary>
        internal static string EmailcontactID {
            get {
                return ResourceManager.GetString("EmailcontactID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ایمیل.
        /// </summary>
        internal static string EmailID {
            get {
                return ResourceManager.GetString("EmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت ایمیل اشخاص.
        /// </summary>
        internal static string EmailPerson {
            get {
                return ResourceManager.GetString("EmailPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ایمیل.
        /// </summary>
        internal static string EmailType {
            get {
                return ResourceManager.GetString("EmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد نوع ایمیل.
        /// </summary>
        internal static string EmailTypeID {
            get {
                return ResourceManager.GetString("EmailTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت نوع ایمیل.
        /// </summary>
        internal static string EmailTypeManagment {
            get {
                return ResourceManager.GetString("EmailTypeManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نوع ایمیل.
        /// </summary>
        internal static string EmailTypeName {
            get {
                return ResourceManager.GetString("EmailTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارکنان.
        /// </summary>
        internal static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن موجود در تصویر فوق را وارد کنید :.
        /// </summary>
        internal static string EnterCaptcha {
            get {
                return ResourceManager.GetString("EnterCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترم ورود.
        /// </summary>
        internal static string EntryTerm {
            get {
                return ResourceManager.GetString("EntryTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری مورد نظر مسدود است!.
        /// </summary>
        internal static string errAccountIsLocked {
            get {
                return ResourceManager.GetString("errAccountIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت اطلاعات وجود ندارد.
        /// </summary>
        internal static string errAddFailed {
            get {
                return ResourceManager.GetString("errAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل مورد نظر را انتخاب کنید.
        /// </summary>
        internal static string errAddFailedFileUploadempty {
            get {
                return ResourceManager.GetString("errAddFailedFileUploadempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت فرمت عکس انتخابی وجود ندارد.
        /// </summary>
        internal static string errAddFailedFileUploadformat {
            get {
                return ResourceManager.GetString("errAddFailedFileUploadformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  عنوان فایل خود را تغییر دهید.
        /// </summary>
        internal static string errAddFailedFileUploadrepeat {
            get {
                return ResourceManager.GetString("errAddFailedFileUploadrepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم فایل انتخابی بیشتر از سایز مجاز است.
        /// </summary>
        internal static string errAddFailedFileUploadsize {
            get {
                return ResourceManager.GetString("errAddFailedFileUploadsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان نرم افزار تکراری است.
        /// </summary>
        internal static string errAddFailedSoftName {
            get {
                return ResourceManager.GetString("errAddFailedSoftName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف اطلاعات وجود ندارد.
        /// </summary>
        internal static string errDeleteFailed {
            get {
                return ResourceManager.GetString("errDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل موردنظر قبلا ثبت شده است.
        /// </summary>
        internal static string errDuplicateEmail {
            get {
                return ResourceManager.GetString("errDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری پیشنهادی قبلا ثبت شده است.
        /// </summary>
        internal static string errDuplicateProposedUsername {
            get {
                return ResourceManager.GetString("errDuplicateProposedUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری مورد نظر قبلا ثبت شده است.
        /// </summary>
        internal static string errDuplicateUsername {
            get {
                return ResourceManager.GetString("errDuplicateUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور معتبر نمی باشد!.
        /// </summary>
        internal static string errInvalidUserPass {
            get {
                return ResourceManager.GetString("errInvalidUserPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسورد ها را درست وارد کنید .
        /// </summary>
        internal static string errNoPasswordsAreNotMatch {
            get {
                return ResourceManager.GetString("errNoPasswordsAreNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان انجام عملیات وجود ندارد!.
        /// </summary>
        internal static string errOperationFailed {
            get {
                return ResourceManager.GetString("errOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه مورد نظر در دسترس نمی باشد.
        /// </summary>
        internal static string errorpage {
            get {
                return ResourceManager.GetString("errorpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل انتخابی تکراری می باشد .
        /// </summary>
        internal static string errRepeatemailTitle {
            get {
                return ResourceManager.GetString("errRepeatemailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره انتخابی تکراری می باشد.
        /// </summary>
        internal static string errRepeatetelTitle {
            get {
                return ResourceManager.GetString("errRepeatetelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان گروه انتخابی تکراری می باشد.
        /// </summary>
        internal static string errRepeatGroupTitle {
            get {
                return ResourceManager.GetString("errRepeatGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان انتخابی تکراری می باشد.
        /// </summary>
        internal static string errRepeatTitle {
            get {
                return ResourceManager.GetString("errRepeatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری انتخابی تکراری می باشد.
        /// </summary>
        internal static string errRepeatuserTitle {
            get {
                return ResourceManager.GetString("errRepeatuserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  رکوردی وجود ندارد.
        /// </summary>
        internal static string errSearch {
            get {
                return ResourceManager.GetString("errSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ویرایش اطلاعات وجود ندارد.
        /// </summary>
        internal static string errUpdateFailed {
            get {
                return ResourceManager.GetString("errUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان دانشکده.
        /// </summary>
        internal static string FacuktyTitle {
            get {
                return ResourceManager.GetString("FacuktyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانشکده ها.
        /// </summary>
        internal static string Faculties {
            get {
                return ResourceManager.GetString("Faculties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد دانشکده.
        /// </summary>
        internal static string FacultyID {
            get {
                return ResourceManager.GetString("FacultyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت دانشکده.
        /// </summary>
        internal static string FacultyManagment {
            get {
                return ResourceManager.GetString("FacultyManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام دانشکده.
        /// </summary>
        internal static string FacultyName {
            get {
                return ResourceManager.GetString("FacultyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام دانشکده.
        /// </summary>
        internal static string FacultyTitle {
            get {
                return ResourceManager.GetString("FacultyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fdg.
        /// </summary>
        internal static string fds {
            get {
                return ResourceManager.GetString("fds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رشته.
        /// </summary>
        internal static string FieldID {
            get {
                return ResourceManager.GetString("FieldID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام رشته.
        /// </summary>
        internal static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته تحصیلی.
        /// </summary>
        internal static string FieldTitle {
            get {
                return ResourceManager.GetString("FieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم نرم افزار.
        /// </summary>
        internal static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور خود را فراموش کرده ام.
        /// </summary>
        internal static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل تصویر.
        /// </summary>
        internal static string ImageFile {
            get {
                return ResourceManager.GetString("ImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن وارد شده صحیح نیست. دوباره تلاش کنید!.
        /// </summary>
        internal static string IncorrectCaptcha {
            get {
                return ResourceManager.GetString("IncorrectCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن رشته.
        /// </summary>
        internal static string InserField {
            get {
                return ResourceManager.GetString("InserField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن اکانت جدید.
        /// </summary>
        internal static string InsertAccount {
            get {
                return ResourceManager.GetString("InsertAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن اکانت.
        /// </summary>
        internal static string InsertAcount {
            get {
                return ResourceManager.GetString("InsertAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن مدیر.
        /// </summary>
        internal static string InsertAdmin {
            get {
                return ResourceManager.GetString("InsertAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن واحد.
        /// </summary>
        internal static string InsertDepartment {
            get {
                return ResourceManager.GetString("InsertDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن  رشته تحصیلی.
        /// </summary>
        internal static string InsertEduField {
            get {
                return ResourceManager.GetString("InsertEduField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن مقطع.
        /// </summary>
        internal static string InsertEduLevel {
            get {
                return ResourceManager.GetString("InsertEduLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن گرایش تحصیلی.
        /// </summary>
        internal static string InsertEduTendency {
            get {
                return ResourceManager.GetString("InsertEduTendency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن ایمیل.
        /// </summary>
        internal static string InsertEmailContact {
            get {
                return ResourceManager.GetString("InsertEmailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن نوع ایمیل.
        /// </summary>
        internal static string InsertEmailType {
            get {
                return ResourceManager.GetString("InsertEmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن کارمند.
        /// </summary>
        internal static string InsertEmployee {
            get {
                return ResourceManager.GetString("InsertEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن دانشکده.
        /// </summary>
        internal static string InsertFaculty {
            get {
                return ResourceManager.GetString("InsertFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن استاد.
        /// </summary>
        internal static string InsertLecturer {
            get {
                return ResourceManager.GetString("InsertLecturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن لینک.
        /// </summary>
        internal static string InsertLink {
            get {
                return ResourceManager.GetString("InsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن سمت.
        /// </summary>
        internal static string InsertRole {
            get {
                return ResourceManager.GetString("InsertRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن نرم افزار جدید.
        /// </summary>
        internal static string InsertSoftware {
            get {
                return ResourceManager.GetString("InsertSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن لینک.
        /// </summary>
        internal static string InsertSoftwareLink {
            get {
                return ResourceManager.GetString("InsertSoftwareLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن دانشجو.
        /// </summary>
        internal static string InsertStudent {
            get {
                return ResourceManager.GetString("InsertStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن شماره تماس.
        /// </summary>
        internal static string InsertTel {
            get {
                return ResourceManager.GetString("InsertTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن تماس.
        /// </summary>
        internal static string InsertTelContact {
            get {
                return ResourceManager.GetString("InsertTelContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن نوع تماس.
        /// </summary>
        internal static string InsertTelType {
            get {
                return ResourceManager.GetString("InsertTelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن گرایش.
        /// </summary>
        internal static string InsertTendency {
            get {
                return ResourceManager.GetString("InsertTendency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اساتید.
        /// </summary>
        internal static string Lecturers {
            get {
                return ResourceManager.GetString("Lecturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدمقطع.
        /// </summary>
        internal static string LevelID {
            get {
                return ResourceManager.GetString("LevelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مقطع تحصیلی.
        /// </summary>
        internal static string LevelName {
            get {
                return ResourceManager.GetString("LevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقطع تحصیلی.
        /// </summary>
        internal static string LevelTitle {
            get {
                return ResourceManager.GetString("LevelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک  برای این نرم افزار ثبت شده است.
        /// </summary>
        internal static string LinkRecordCount {
            get {
                return ResourceManager.GetString("LinkRecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سامانه.
        /// </summary>
        internal static string LoginToSystem {
            get {
                return ResourceManager.GetString("LoginToSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت واحد اداری معاونت.
        /// </summary>
        internal static string ManageDepartment {
            get {
                return ResourceManager.GetString("ManageDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت رشته های تحصیلی.
        /// </summary>
        internal static string ManageEduField {
            get {
                return ResourceManager.GetString("ManageEduField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت سطح تحصیلی.
        /// </summary>
        internal static string ManageEduLevel {
            get {
                return ResourceManager.GetString("ManageEduLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت گرایش.
        /// </summary>
        internal static string ManageEduTendency {
            get {
                return ResourceManager.GetString("ManageEduTendency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیرت ایمیل.
        /// </summary>
        internal static string ManageEmail {
            get {
                return ResourceManager.GetString("ManageEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت ایمیل اشخاص.
        /// </summary>
        internal static string ManageEmailContact {
            get {
                return ResourceManager.GetString("ManageEmailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت نوع ایمیل.
        /// </summary>
        internal static string ManageEmailType {
            get {
                return ResourceManager.GetString("ManageEmailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کارمند.
        /// </summary>
        internal static string ManageEmploye {
            get {
                return ResourceManager.GetString("ManageEmploye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت دانشکده.
        /// </summary>
        internal static string ManageFaculty {
            get {
                return ResourceManager.GetString("ManageFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت استاد.
        /// </summary>
        internal static string ManageLecture {
            get {
                return ResourceManager.GetString("ManageLecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت اکانت مدیران سامانه.
        /// </summary>
        internal static string ManagePersonAdmin {
            get {
                return ResourceManager.GetString("ManagePersonAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت سمت.
        /// </summary>
        internal static string ManageRole {
            get {
                return ResourceManager.GetString("ManageRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت دانشجویان.
        /// </summary>
        internal static string ManageStudent {
            get {
                return ResourceManager.GetString("ManageStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت شماره تماس.
        /// </summary>
        internal static string ManageTel {
            get {
                return ResourceManager.GetString("ManageTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت تماس اشخاص.
        /// </summary>
        internal static string ManageTelContact {
            get {
                return ResourceManager.GetString("ManageTelContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت نوع شماره تماس.
        /// </summary>
        internal static string ManageTelType {
            get {
                return ResourceManager.GetString("ManageTelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت اکانت وب سرویس.
        /// </summary>
        internal static string ManageWebService {
            get {
                return ResourceManager.GetString("ManageWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت سامانه.
        /// </summary>
        internal static string Menuadmins {
            get {
                return ResourceManager.GetString("Menuadmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروههای نرم افزاری.
        /// </summary>
        internal static string Menugroups {
            get {
                return ResourceManager.GetString("Menugroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت لینک ها.
        /// </summary>
        internal static string Menulinks {
            get {
                return ResourceManager.GetString("Menulinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت نرم افزار.
        /// </summary>
        internal static string Menusoftwares {
            get {
                return ResourceManager.GetString("Menusoftwares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت حسا ب های کاربردی.
        /// </summary>
        internal static string MgrAccounts {
            get {
                return ResourceManager.GetString("MgrAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اطلاعات با موفقیت انجام شد.
        /// </summary>
        internal static string msgAddSuccessfull {
            get {
                return ResourceManager.GetString("msgAddSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف اطلاعات با موفقیت انجام شد.
        /// </summary>
        internal static string msgDeleteSuccessfull {
            get {
                return ResourceManager.GetString("msgDeleteSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش اطلاعات با موفقیت انجام شد.
        /// </summary>
        internal static string msgUpdateSuccessfull {
            get {
                return ResourceManager.GetString("msgUpdateSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        internal static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نرم افزار جدید.
        /// </summary>
        internal static string NewSoftInsert {
            get {
                return ResourceManager.GetString("NewSoftInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری پیشنهادی.
        /// </summary>
        internal static string NewUserName {
            get {
                return ResourceManager.GetString("NewUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید رمز عبور.
        /// </summary>
        internal static string PassRepeat {
            get {
                return ResourceManager.GetString("PassRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید رمز عبور.
        /// </summary>
        internal static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to l.
        /// </summary>
        internal static string pe {
            get {
                return ResourceManager.GetString("pe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشخاص.
        /// </summary>
        internal static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیران سامانه پرسنلی.
        /// </summary>
        internal static string PersonAdmins {
            get {
                return ResourceManager.GetString("PersonAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد بازدید کنندگان .
        /// </summary>
        internal static string portalvisited {
            get {
                return ResourceManager.GetString("portalvisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد نرم افزارهای موجود در پرتال.
        /// </summary>
        internal static string programcount {
            get {
                return ResourceManager.GetString("programcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد در این بخش ثبت شده است.
        /// </summary>
        internal static string RecordCount {
            get {
                return ResourceManager.GetString("RecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        internal static string RegDate {
            get {
                return ResourceManager.GetString("RegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ثبت.
        /// </summary>
        internal static string RegTime {
            get {
                return ResourceManager.GetString("RegTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارشگیری.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد سمت.
        /// </summary>
        internal static string RoleID {
            get {
                return ResourceManager.GetString("RoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت سمت ها.
        /// </summary>
        internal static string RoleManagment {
            get {
                return ResourceManager.GetString("RoleManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سمت.
        /// </summary>
        internal static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سمت ها.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد از این بخش انتخاب شده است.
        /// </summary>
        internal static string SelectRecordCount {
            get {
                return ResourceManager.GetString("SelectRecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد نرم افزار.
        /// </summary>
        internal static string SoftwareID {
            get {
                return ResourceManager.GetString("SoftwareID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویرنرم افزار.
        /// </summary>
        internal static string SoftwareImage {
            get {
                return ResourceManager.GetString("SoftwareImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان نرم افزار.
        /// </summary>
        internal static string SoftwareName {
            get {
                return ResourceManager.GetString("SoftwareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره دانشجویی.
        /// </summary>
        internal static string StudentCode {
            get {
                return ResourceManager.GetString("StudentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد دانشجو.
        /// </summary>
        internal static string StudentID {
            get {
                return ResourceManager.GetString("StudentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانشجویان.
        /// </summary>
        internal static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت تماس ها.
        /// </summary>
        internal static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس.
        /// </summary>
        internal static string TelID {
            get {
                return ResourceManager.GetString("TelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس.
        /// </summary>
        internal static string TelNumber {
            get {
                return ResourceManager.GetString("TelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت تماس اشخاص.
        /// </summary>
        internal static string TelPerson {
            get {
                return ResourceManager.GetString("TelPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت نوع تماس.
        /// </summary>
        internal static string TelType {
            get {
                return ResourceManager.GetString("TelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد نوع تماس.
        /// </summary>
        internal static string TelTypeID {
            get {
                return ResourceManager.GetString("TelTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نوع تماس.
        /// </summary>
        internal static string TelTypeName {
            get {
                return ResourceManager.GetString("TelTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گرایش ها.
        /// </summary>
        internal static string Tendencies {
            get {
                return ResourceManager.GetString("Tendencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد گرایش.
        /// </summary>
        internal static string TendencyID {
            get {
                return ResourceManager.GetString("TendencyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام گرایش.
        /// </summary>
        internal static string TendencyName {
            get {
                return ResourceManager.GetString("TendencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گرایش.
        /// </summary>
        internal static string TendencyTitle {
            get {
                return ResourceManager.GetString("TendencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        internal static string UpdateGroup {
            get {
                return ResourceManager.GetString("UpdateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادامه.
        /// </summary>
        internal static string UserHyperLink {
            get {
                return ResourceManager.GetString("UserHyperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد کاربر.
        /// </summary>
        internal static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UserProfileMenuItem {
            get {
                return ResourceManager.GetString("UserProfileMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد نوع کاربر.
        /// </summary>
        internal static string UserTypeID {
            get {
                return ResourceManager.GetString("UserTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورژن.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده.
        /// </summary>
        internal static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت vpn.
        /// </summary>
        internal static string vpn {
            get {
                return ResourceManager.GetString("vpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کدVPN.
        /// </summary>
        internal static string VPNID {
            get {
                return ResourceManager.GetString("VPNID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت vpn.
        /// </summary>
        internal static string VPNManagment {
            get {
                return ResourceManager.GetString("VPNManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش VPN.
        /// </summary>
        internal static string VPNUpdate {
            get {
                return ResourceManager.GetString("VPNUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکانت وب سرویس.
        /// </summary>
        internal static string WebServiceAccount {
            get {
                return ResourceManager.GetString("WebServiceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت اکانت وب سرویس.
        /// </summary>
        internal static string WebServiceAccountManagment {
            get {
                return ResourceManager.GetString("WebServiceAccountManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عزیز ، خوش آمدید.
        /// </summary>
        internal static string WelcomeDearUser {
            get {
                return ResourceManager.GetString("WelcomeDearUser", resourceCulture);
            }
        }
    }
}
